USE iTLoads;
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE dbo.CheckOrgStructForPositionsWithoutEmp_No
AS
SET NOCOUNT ON;
SELECT *
FROM OrgStruct
WHERE [OBJECT] = 'POSITION'
	AND NOT NAME LIKE '(%';
GO
