USE iTLoads;
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
ALTER VIEW dbo.iT01_00_Organisation_Structure
AS
SELECT [OBJECT]
	,CASE
		WHEN [OBJECT] = 'POSITION'
		THEN LTRIM(RTRIM(SUBSTRING(NAME, CHARINDEX(')', NAME) + 1, 255)))
		ELSE NAME
	END AS NAME
	,POST_NO
	,[START_DATE]
	,PARENT_OBJECT
	,PARENT_POST_NO
	,PARENT_NAME
FROM dbo.OrgStruct
WHERE NOT ([OBJECT] = 'POSITION' AND POST_NO LIKE 'PREV%')
GO
