USE iTLoads;
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
ALTER VIEW iT06_01_AttachEmployees2Structure
AS
--WITH UniqueContractJobs
--AS
--(
--	SELECT EMP_NO, JOB_TITLE, MAX(CONTRACT_NO) AS CONTRACT_NO
--	FROM dbo.APPOINTMENTS
--	WHERE CURRENT_INDICATOR = 'C'
--	GROUP BY EMP_NO, JOB_TITLE
--)
WITH People
AS
(
	SELECT 
		X.PER_REF_NO AS PER_REF_NO
		,'PERSON' AS [OBJECT]
		,RTRIM(P.INITIALS) + ' ' + RTRIM(P.SURNAME) AS NAME
		,CONVERT(char(8), P.DATE_OF_START, 112) AS [START_DATE]
		,'POSITION' AS PARENT_OBJECT
		,'' AS PARENT_NAME
		,PR.iTrentPositionRef_LOAD AS PARENT_POST_NO
		--,RTRIM(X.PER_REF_NO) + '-' + CAST(XA.CONTRACT_NO AS varchar(10)) AS POS_OCC_REF_NO
		--,CASE
		--	WHEN PR.IsMultiContract = 1
		--	THEN PR.POS_OCC_REF_NO
		--	ELSE ''
		--END AS POS_OCC_REF_NO
		--,'' AS POS_OCC_REF_NO
		 ,PR.POS_OCC_REF_NO
		--,ROW_NUMBER() OVER (PARTITION BY X.PER_REF_NO ORDER BY P.DATE_OF_START) AS rn
	FROM dbo.PERSON P
		CROSS APPLY
		(
			VALUES
			(
				--CASE
				--	WHEN LEN(P.EMP_NO) < 6
				--	THEN RIGHT('00000' + RTRIM(P.EMP_NO), 6)
				--	ELSE P.EMP_NO
				--END
				RIGHT('00000' + LTRIM(RTRIM(P.EMP_NO)), 6)
			)
		) X (PER_REF_NO)
		JOIN dbo.EMP_NO_X_POS_REF PR
			ON X.PER_REF_NO = PR.EMP_NO

		--LEFT JOIN UniqueContractJobs CJ
		--	ON P.EMP_NO = CJ.EMP_NO
		--		AND PR.JOB_TITLE COLLATE SQL_Latin1_General_CP1_CI_AS = CJ.JOB_TITLE
		--CROSS APPLY (VALUES (COALESCE(CJ.CONTRACT_NO, 1))) XA (CONTRACT_NO)
	WHERE P.PERSON_STATUS NOT LIKE 'L%'
		AND LEN(P.EMP_NO) < 7
		--AND L.GreyChair = 'N'
)
SELECT PER_REF_NO, [OBJECT], NAME, [START_DATE], PARENT_OBJECT, PARENT_NAME, PARENT_POST_NO
	,POS_OCC_REF_NO
	--,CASE
	--	WHEN PARENT_POST_NO LIKE 'PREV%'
	--	THEN ''
	--	ELSE PER_REF_NO + CHAR(64 + rn)
	--END AS POS_OCC_REF_NO
FROM People
GO
