USE iTLoads;
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
ALTER VIEW dbo.iT08_00_StudentLoans
AS
SELECT 
	RTRIM(X.PER_REF_NO) AS PER_REF_NO
	,CASE
		WHEN C.ORDER_DATE < P.DATE_OF_START
		THEN CONVERT(char(8), P.DATE_OF_START, 112)
		ELSE CONVERT(char(8), C.ORDER_DATE, 112)
	END AS PAYMENT_START_DATE
	,COALESCE(CONVERT(char(8), C.STUDENT_LOAN_STOP_DATE, 112), '') AS PAYMENT_STOP_DATE
	-- Looks like C.COURT_REF used for both stop and start reason
	-- Text is free form - may need to convert to list
	--,CASE
	--	WHEN C.STUDENT_LOAN_STOP_DATE IS NULL
	--	THEN COALESCE(RTRIM(C.COURT_REF), '')
	--	ELSE ''
	--END AS START_REASON
	,'Start notice received' AS START_REASON
	,CASE
		WHEN C.STUDENT_LOAN_STOP_DATE IS NOT NULL
		THEN 'Received SL2' --COALESCE(RTRIM(C.COURT_REF), '')
		ELSE ''
	END AS STOP_REASON
	,CASE
		WHEN C.ORDER_TYPE = 'R'
		THEN 1
		ELSE 2
	END AS PARTY_ID
FROM dbo.PERSON P
	JOIN dbo.COURT_ORDER C
		ON P.EMP_NO = C.EMP_NO
			AND C.COURT = 'SLC'
	--LEFT JOIN dbo.SGUL_AGRESSO_RESOURCE R
	--	ON P.EMP_NO = R.EMP_NO
	CROSS APPLY
	(
		VALUES
		(
			--CASE
			--	WHEN LEN(COALESCE(R.RESOURCE_NO, P.EMP_NO)) < 6
			--	THEN RIGHT('00000' + RTRIM(COALESCE(R.RESOURCE_NO, P.EMP_NO)), 6)
			--	ELSE COALESCE(R.RESOURCE_NO, P.EMP_NO)
			--END
			LTRIM(RTRIM(P.EMP_NO))
		)
	) X (PER_REF_NO)
WHERE P.PERSON_STATUS NOT LIKE 'L%'
	AND LEN(P.EMP_NO) < 7
	AND
	(
		C.STUDENT_LOAN_STOP_DATE IS NULL
		OR C.STUDENT_LOAN_STOP_DATE >= '20170401'
	)
GO
