USE iTLoads;
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
ALTER VIEW dbo.iT10_03_Annual_Salary_Payscale_with_Grade
AS
SELECT
	RTRIM(X.PER_REF_NO) AS PER_REF_NO
	,'POSITION' AS [OBJECT]
	,CONVERT(char(8), A.CHANGE_DATE, 112) AS START_DATE
	,'PAY' AS [GROUP]
	,'PAY' AS [TYPE]
	-- get iTrent name here!!
	,CASE
		WHEN A.SCALE_CODE = 'AFC NEW'
		THEN 'AFC'
		WHEN A.SCALE_CODE = 'NEWCONSULT'
		THEN COALESCE(RTRIM(A.GRADE), '')
		ELSE RTRIM(A.SCALE_CODE)
	END AS VALUE6
	,COALESCE(CAST(A.SPINAL_POINT AS varchar(10)), '') AS VALUE10
	-- get iTrent name here!!
	,COALESCE(RTRIM(A.GRADE), '') AS VALUE12
	,COALESCE(CONVERT(char(8), A.SALARY_REVIEW_DATE, 112), '') AS VALUE16
	,COALESCE(M.POS_REF_NO, '') AS POST_NO
FROM dbo.PERSON P
	CROSS APPLY
	(
		VALUES
		(
			--CASE
			--	WHEN LEN(P.EMP_NO) < 6
			--	THEN RIGHT('00000' + RTRIM(P.EMP_NO), 6)
			--	ELSE P.EMP_NO
			--END
			LTRIM(RTRIM(P.EMP_NO))
		)
	) X (PER_REF_NO)
	JOIN dbo.APPOINTMENTS A
		ON P.EMP_NO = A.EMP_NO
	JOIN dbo.CONTRACT_DETAILS D
		ON A.EMP_NO = D.EMP_NO
			AND A.CONTRACT_NO = D.CONTRACT_NO
	LEFT JOIN dbo.MultiPaidContracts M
		ON A.EMP_NO = M.EMP_NO
			AND A.CONTRACT_NO = M.CONTRACT_NO
WHERE P.PERSON_STATUS NOT LIKE 'L%'
	AND D.IS_MASTER = 'Y'
	--AND A.SCALE_CODE IN ('CLINICAL','CLINICAL+','NON-STAFF','SGUL','SGUL PSC','CLINICAL++','AFC NEW','NEWCONSULT','SGUL TUPE')
	AND A.SCALE_CODE IN ('CLINICAL','CLINICAL+','SGUL','SGUL PSC','CLINICAL++','AFC NEW','NEWCONSULT','SGUL TUPE')
	--Note these!!!!
	--AND NOT (A.SPINAL_POINT IS NULL OR A.GRADE IS NULL)
	AND
	(
		A.CURRENT_INDICATOR IN ('C','L')
		OR
		(
			A.CURRENT_INDICATOR = 'J'
			AND
			(
				NOT EXISTS
				(
						SELECT 1
						FROM dbo.APPOINTMENTS A1
						WHERE A1.EMP_NO = A.EMP_NO
							AND A1.CURRENT_INDICATOR = 'C'		
				)
				OR A.CHANGE_DATE <= CURRENT_TIMESTAMP
			)
		)
	)
	AND EXISTS
	(
		SELECT 1
		FROM dbo.REFNO RN
		WHERE RN.PAYROLL_EMP_NO = P.EMP_NO
			AND RN.PAY_GROUP = 'MTH'
	);
GO
