USE iTLoads;
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
ALTER VIEW dbo.iT12_00_Inheritance_Work_Patterns
AS
WITH WSP
AS
(
	SELECT WORK_SHIFT_CODE, STANDARD_HOURS, WORK_SHIFT_CODE_NEW
	FROM dbo.WP_WSP
	WHERE WEEK_NUMBER = 1
		AND WORK_SHIFT_CODE_NEW <> 'm7t7w7th7f7'
)
SELECT LTRIM(RTRIM(E.EMP_NO)) AS PER_REF_NO
	,'POSITION' AS [OBJECT]
	,CONVERT(char(8), DATE_EFFECTIVE, 112) AS [START_DATE]
	,'SWP' AS [GROUP]
	,'Working Pattern' AS [TYPE]
	,LTRIM(RTRIM(WORK_SHIFT_CODE_NEW)) AS VALUE1
	,'Week ' + CAST(WORK_SHIFT_START_WEEK as char(1))
		+ ' / Day ' + CAST(WORK_SHIFT_START_DAY as varchar(2)) AS VALUE2
	,'' AS POST_NO
FROM dbo.WP_EWSS E
	JOIN WSP P
		ON E.WORK_SHIFT_CODE  = P.WORK_SHIFT_CODE
			AND E.STANDARD_HOURS = P.STANDARD_HOURS;
GO
