USE iTLoads;
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE VIEW dbo.iT25_01_Taxable_Pay
AS
SELECT PER_REF_NO
	,'Taxable pay' AS ACCUMULATOR
	,TaxablePay AS INPUT_CASH
	,'ACC' AS HISTORY_TYPE
FROM dbo.PaySlipInfo
WHERE TaxablePay > 0;
GO
