USE iTLoads;
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE VIEW dbo.iT25_11_Pension_Employer_Contributions
AS
SELECT PER_REF_NO
	,SchemeName + ' - ER' AS ELEMENT_NAME
	,YTD_ER_VALUE AS INPUT_CASH
	,'ELE' AS HISTORY_TYPE
FROM dbo.PaySlipPensions
WHERE IsAVC = 'N'
	AND YTD_ER_VALUE > 0;
GO
