USE iTLoads;
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE VIEW dbo.iT25_06_Niable_Pay
AS
SELECT PER_REF_NO
	,'Niable pay' AS ACCUMULATOR
	,NiablePay AS INPUT_CASH
	,'ACC' AS HISTORY_TYPE
FROM dbo.PaySlipInfo
WHERE NiablePay > 0;
GO
