USE iTLoads;
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE VIEW dbo.iT25_02_Tax
AS
SELECT PER_REF_NO
	,'Tax' AS ELEMENT_NAME
	,Tax AS INPUT_CASH
	,'ELE' AS HISTORY_TYPE
FROM dbo.PaySlipInfo
WHERE Tax > 0;
GO
