USE iTLoads;
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE VIEW dbo.iT25_08_National_Insurance_to_ET
AS
SELECT PER_REF_NO
	,'Niable pay' AS ELEMENT_NAME
	,NI2ET AS INPUT_CASH
	,'ELE' AS HISTORY_TYPE
	,'EEET' AS [TYPE]
	,NI_CATEGORY
FROM dbo.PaySlipInfo
WHERE NI2ET > 0;
GO
