USE iTLoads;
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
ALTER VIEW dbo.iT26_00_Leaver_Details
AS
SELECT X.PER_REF_NO
	,COALESCE(CONVERT(char(8), P.DATE_OF_LEAVING, 112), '') AS [END_DATE]
	,COALESCE(RTRIM(R.REASON), 'Unknown') AS LEAVING_REASON
FROM dbo.PERSON P
	LEFT JOIN dbo.LEAVING_REASON R
		ON P.REASON_FOR_LEAVING = R.REASON_CODE
	CROSS APPLY
	(
		VALUES
		(
			--CASE
			--	WHEN LEN(P.EMP_NO) < 6
			--	THEN RIGHT('00000' + RTRIM(P.EMP_NO), 6)
			--	ELSE P.EMP_NO
			--END
			RIGHT('00000' + LTRIM(RTRIM(P.EMP_NO)), 6)
		)
	) X (PER_REF_NO)
WHERE LEN(P.EMP_NO) < 7
	AND P.PERSON_STATUS LIKE 'L%' AND P.DATE_OF_LEAVING >= '20170401'
	-- only need these to start with
	AND EXISTS
	(
		SELECT 1
		FROM dbo.REFNO RN
		WHERE RN.PAYROLL_EMP_NO = P.EMP_NO
			AND RN.PAY_GROUP = 'MTH'
	);
