USE [iTLoads]
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
ALTER VIEW dbo.iT99_12_01_01_HESA_Return
AS
--12.1.1 User Defined Fields - File Formats
SELECT RIGHT('00000' + RTRIM(R.EMP_NO), 6) AS PER_REF_NO
	,'HESA Return' AS [GROUP]
	,'Include in HESA return?' AS FIELD
	,CASE WHEN X.HESA_ELIGIBLE = 'Y' THEN 'Y' ELSE 'N' END AS VALUE
	,'PERSON' AS ITEM_TYPE --or POST?
FROM dbo.PERSON P
	OUTER APPLY
	(
		SELECT TOP (1) A.HESA_ELIGIBLE
		FROM dbo.APPOINTMENTS A
		WHERE A.EMP_NO = P.EMP_NO
			AND A.HESA_ELIGIBLE = 'Y'
	) X
	JOIN dbo.SGUL_AGRESSO_RESOURCE R
		ON P.EMP_NO = R.EMP_NO
WHERE LEN(P.EMP_NO) < 7
	AND
	(
		P.PERSON_STATUS NOT LIKE 'L%'
		OR
		(P.PERSON_STATUS LIKE 'L%' AND P.DATE_OF_LEAVING >= '20170401')
	);
GO
