USE [iTLoads]
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
ALTER VIEW dbo.iT99_12_01_01_Agresso_Number
AS
--12.1.1 User Defined Fields - File Formats
SELECT RIGHT('00000' + RTRIM(R.EMP_NO), 6) AS PER_REF_NO
	,'Agresso Number' AS [GROUP]
	,'Agresso Number' AS FIELD
	,CAST(R.RESOURCE_NO AS int) AS VALUE
	,'PERSON' AS ITEM_TYPE
FROM dbo.PERSON P
	JOIN dbo.SGUL_AGRESSO_RESOURCE R
		ON P.EMP_NO = R.EMP_NO
WHERE LEN(P.EMP_NO) < 7
	AND R.EMP_NO <> R.RESOURCE_NO
	AND
	(
		P.PERSON_STATUS NOT LIKE 'L%'
		OR
		(P.PERSON_STATUS LIKE 'L%' AND P.DATE_OF_LEAVING >= '20170401')
	);
GO
