USE [iTLoads]
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
ALTER VIEW dbo.iT99_4_8_1_Fixed_Term_End_Dates
AS
SELECT P.EMP_NO AS PER_REF_NO
	,CONVERT(char(8), A.FIXED_TERM_END_DATE, 112) AS EXPECTED_OCCUPANCY_END_DATE
	,'POSITION' AS [OBJECT]
	-- Need POST_NO for multiple contact.
FROM dbo.PERSON P
	JOIN dbo.APPOINTMENTS A
		ON P.EMP_NO = A.EMP_NO
			AND A.CURRENT_INDICATOR = 'C'
			AND FIXED_TERM_END_DATE > '20170801'
WHERE P.PERSON_STATUS NOT LIKE 'L%'
	AND
	(
		A.CURRENT_INDICATOR IN ('C','L')
		OR
		(
			A.CURRENT_INDICATOR = 'J'
			AND
			(
				NOT EXISTS
				(
						SELECT 1
						FROM dbo.APPOINTMENTS A1
						WHERE A1.EMP_NO = A.EMP_NO
							AND A1.CURRENT_INDICATOR = 'C'		
				)
				OR A.CHANGE_DATE <= CURRENT_TIMESTAMP
			)
		)
	)
	AND EXISTS
	(
		SELECT 1
		FROM dbo.REFNO RN
		WHERE RN.PAYROLL_EMP_NO = P.EMP_NO
			AND RN.PAY_GROUP = 'MTH'
	);
GO
